### ISSUE TITLE
Can't connect to Win XP machine with v1.8.0 and 1.9.0

### ISSUE THREAD

**Issue by yustas82** [iSnackyCracky/KeePassRDP#5] opened 2019-12-20 17:20 UTC
I know that Win XP is dropped but some users are still using it.
With version 1.8.0 and 1.9.0 I wasn't able to connect to Win XP x86 from Win 10 x64 using the saved credentials.
With 1.7.2 everything works fine with using the same machines.
If needed I can provide more information on this.

**Comment by iSnackyCracky** [comment] 2019-12-21 16:44
Hi @yustas82,
that's strange because the relevant code for using the credentials itself shouldn't have changed between these versions.
I'm going to set up an XP VM to do some testing.

Since it stopped working with v1.8.0 (which implemented reference-resolving) - are you using [KeePass references](https://keepass.info/help/base/fieldrefs.html) with the relevant connections/credentials?

**Comment by iSnackyCracky** [comment] 2019-12-23 13:44
Hey @yustas82,

I've now set up a VM to test this and was not able to reproduce the issue.
If I choose to connect with credentials - I get logged in instantly.

Could you maybe also check, if the connection takes a while? The saved Credentials get removed from the credential-store after ~10seconds; if the connection isn't already established until then, the machine will ask for credentials.

There was a bug which prevented the removal from happening until v1.7.0 (fixed in v1.7.1) maybe you would need more time before the credentials get removed - I am planning to implement this in a near future release.

**Comment by iSnackyCracky** [comment] 2021-02-03 11:55
I'm going to close this issue as there was no activity for over 1 year now.
If you're still facing the same issue, feel free to open a new one.

**Closed by iSnackyCracky** 2021-02-03 11:55 UTC
Labels: bug, needs information
