### ISSUE TITLE
Asking every time about another cred's (KeePassRDP v2.2)

### ISSUE THREAD

**Issue by mrkingmidas** [iSnackyCracky/KeePassRDP#37] opened 2024-03-13 19:04 UTC
**Describe the bug**
After last update to KeePassRDP v2.2 create asking every time about another cred's

**To Reproduce**
1. Connect to any connection by button
2.  Running normal connection and show question, that showing every time

**Expected behavior**
Does not show question about another cred's. May be option for that.

**Screenshots**
![Demo](https://github.com/iSnackyCracky/KeePassRDP/assets/125803340/5effec2e-9930-4553-a43f-a1d115733d6e)

**Additional context**
All combinations in Options with checkboxes in "Credentials" try, but question still exists

**Comment by NETertainer** [comment] 2024-03-13 19:20
Are you sure the behavior changed from v2.1? The logic behind has not been modified.

**Comment by mrkingmidas** [comment] 2024-03-14 07:13
- Yes, I checked the copy now - there is no such question. But some servers with “gateway” and authentication there ask for a login/password in any case. Although I haven't asked before. In version 2.2 it doesn’t ask, but when you connect to any RDP, a connection is made and this question is immediately shown, in which you need to say “no”, in response to the answer another connection is launched and the first one is closed.
- Sometimes this error is also shown [https://i.imgur.com/sV3i2k4.png](https://i.imgur.com/sV3i2k4.png)

**Comment by NETertainer** [comment] 2024-03-14 07:47
This is how the detection works:

UUID of entry to connect to:
https://github.com/iSnackyCracky/KeePassRDP/blob/b5182e99cd44bc1b258dd6039b2b6d892f7b779f/KeePassRDP/KprConnectionManager.cs#L349
UUID of selected credential entry:
https://github.com/iSnackyCracky/KeePassRDP/blob/b5182e99cd44bc1b258dd6039b2b6d892f7b779f/KeePassRDP/KprConnectionManager.cs#L405
Show warning if a former task with that name is still active:
https://github.com/iSnackyCracky/KeePassRDP/blob/b5182e99cd44bc1b258dd6039b2b6d892f7b779f/KeePassRDP/KprConnectionManager.cs#L491
Remove task after mstsc.exe exits:
https://github.com/iSnackyCracky/KeePassRDP/blob/b5182e99cd44bc1b258dd6039b2b6d892f7b779f/KeePassRDP/KprConnectionManager.cs#L1208

So even if the task is not removed it will be ignored if it has finished. The question is why would that task not finish.
Can you please check that there are no running mstsc.exe processes after you close the connection?
And could you try to translate the error message, i really don´t know how to type the letters :smile:.

**Comment by massimobalestra** [comment] 2024-03-14 13:17
I confirm this bug and I confirm it did not happen on the previous version.
Also it happens only with the button and not with the keyboard shortcut.
And it did not happen in the previous version.

**Comment by massimobalestra** [comment] 2024-03-14 17:57
Yes, I am working on Windows 11 but, no, it is not the credential picker opening a second time, it is simply like I pressed the toolbar button a second time:
![image](https://github.com/iSnackyCracky/KeePassRDP/assets/24854781/429ab9e0-39f3-42f0-86cf-a265ac070e10)
And this behavior doe not appear if I use the Keyboard shortcut.

**Comment by mrkingmidas** [comment] 2024-03-15 07:08
> So even if the task is not removed it will be ignored if it has finished. The question is why would that task not finish. Can you please check that there are no running mstsc.exe processes after you close the connection? And could you try to translate the error message, i really don´t know how to type the letters 😄.

- `mstsc.exe` closes all (in task manager check it)
- Text of error translated to english - "Access to the liquidated object is impossible"
- Working on Win10 1909 x64
- YJn "toolbar button" - "question", on "hotkey" - "connect silently fine"

**Comment by NETertainer** [comment] 2024-03-15 07:14
I was able to identify the root cause and we will fix this asap.

**Comment by NETertainer** [comment] 2024-03-15 08:01
Fixed with v2.2.1.

**Closed by NETertainer** 2024-03-15 08:01 UTC
Labels: bug, work in progress
